#ifndef POLARIS_SHADER_MANAGER
#define POLARIS_SHADER_MANAGER

#include <cstdint>
#include <format>
#include <optional>
#include <string_view>
#include <span>

namespace polaris::vk {

using ShaderData = std::span<const uint8_t>;

struct ShaderInfo {
  std::string_view name;
  ShaderData data;

  constexpr ShaderInfo(std::string_view n, ShaderData d) noexcept : name(n), data(d) {}
};

// everything in this class *could* be constexpr if I moved the shader arrays into a header and included it
// but I think its neater to keep them in a separate TU
class ShaderManager { // NOLINT(hicpp-special-member-functions,cppcoreguidelines-special-member-functions)
 public:
  ShaderManager() = delete;
  ~ShaderManager() = delete;

  // defined in file generated by cmake
  [[nodiscard]] static std::span<const ShaderInfo> shaders() noexcept;

  [[nodiscard]] static std::optional<ShaderData> get(std::string_view name) noexcept {
    auto shaders_list = shaders();
    auto it = std::ranges::find(shaders_list, name, &ShaderInfo::name);
    return it != shaders_list.end() ? std::optional{it->data} : std::nullopt;
  }

  [[nodiscard]] static std::optional<ShaderData> getVert(std::string_view base) noexcept {
    return get(appendStr(base, ".vert"));
  }

  [[nodiscard]] static std::optional<ShaderData> getFrag(std::string_view base) noexcept {
    return get(appendStr(base, ".frag"));
  }

 private:
  static constexpr std::string appendStr(std::string_view base, std::string_view suffix) noexcept {
    std::string name;
    name.reserve(base.size() + suffix.size());
    name.append(base);
    name.append(suffix);
    return name;
  }
};
}  // namespace polaris::vk
#endif
